### ISSUE TITLE
Silverstripe V4 Crazy Egg Integration

### ISSUE THREAD

**Issue by Tisoy21** [silverstripe/silverstripe-crazy-egg#7]
Hello, i have a problem about integration on silverstripe v4 and crazy egg, i already skim on this repo:

https://github.com/silverstripe/silverstripe-crazy-egg.git

on my , "dev/build?flush=all", i got 500 internal server error, i dont know whats the root of my issue, please help :(

**Comment by Tisoy21** [comment]
PHP Fatal error:  Declaration of SilverStripe\CrazyEgg\RequestFilter::preRequest(SilverStripe\Control\HTTPRequest $request, SilverStripe\Control\Session $session, SilverStripe\ORM\DataModel $model) must be compatible with SilverStripe\Control\RequestFilter::preRequest(SilverStripe\Control\HTTPRequest $request) in /Applications/MAMP/htdocs/pulse/vendor/silverstripe/crazy-egg/src/RequestFilter.php on line 12

Here's my response server logs on my end

**Comment by robbieaverill** [comment]
The RequestFilter method signature changed between the time this was upgraded to SS4 (early beta days I think) and stable, which was causing this issue.

The RequestFilter API is deprecated now anyway in favour of HTTP middlewares. I've made a PR to update this module to use a middleware instead at #8

Thanks for raising the issue @Tisoy21!

**Comment by Tisoy21** [comment]
w8 sir which one i change ? @robbieaverill

**Comment by Tisoy21** [comment]
okay sir thanks! 😀
how do i know if that crazy egg add-ons sir have successfull building when
done run "dev/build?flush=all" ?
where i can access the crazy egg tabs in SS CMS ?

**Comment by robbieaverill** [comment]
@Tisoy21 you can now run `composer update silverstripe/crazy-egg` and it should work for you.

Please ensure you read the documentation, that'll tell you how to use the module =)

**Comment by Tisoy21** [comment]
is the module can create a snapshots in Silverstripe CMS that syncs the
data from my end to our crazy egg account ?
